services:
  postgres:
    container_name: postgres_container
    image: postgres:16.11-alpine3.23
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-ticket}
    volumes:
       - postgres:/data/postgres-ticket
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin-ticket

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_HOST=0.0.0.0 
      - REDISINSIGHT_ACCEPT_LICENSE=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  postgres:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    redis-data:
    redisinsight-data: