spring.application.name=gateway
server.port=8080

# Service URLs
services.auth-url=http://localhost:8001
services.booking-url=http://localhost:8002
services.event-url=http://localhost:8003
services.notify-url=http://localhost:8004
services.payment-url=http://localhost:8005

# Gateway Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.com.example.gateway=INFO
