spring.application.name=payment
server.port=8005
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket?currentSchema=payment_schema
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=payment_schema
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Đảm bảo schema được tạo nếu chưa tồn tại
spring.sql.init.mode=always