spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: auth_user
    password: auth_password_123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: auth_schema
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

# SpringDoc Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/auth/v3/api-docs
  swagger-ui:
    enabled: false # Disable local Swagger UI, chỉ dùng centralized tại Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  expiration: 86400000
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC/VPsMO3syzpPI
    L8FDt0qN4x656PS4TIwHLCz4T14nissqpx24L+ZWET7UxwAma1Q61zWb4cJAuPBZ
    x3xkhU2ucdBvWamxbB2n9AwKuQYoC9jjuCP6fK6jQJjf+aWH/lbHQFy5nvbMl1fs
    6f1eAVG14s0Mct9fmeK4I+VCdQvPfaROXPq8kModSFrdtB9xqgaQnLXsTLscqTRf
    CEe3ojkDRwt147tJnOeA8y68AkRj1T2tEn4H/rNPu7RZm9ZFqYVoQ9EvN48Rp/Wu
    2gI1dAVo50ewEjmvvduHTAClv0h0bihK+5rorkz5L3RkM0TnnRWeDsPyYDKXR/al
    Ngo8tS/JAgMBAAECggEAC12L8CUUY2c8Bhc4HsKjjhwgtiBtcQkzBDYOkc19JVIs
    UWNN86P8xb4OgmszyhR0E263Q4Q8msWhmWOtMvdsLuGZ5RNpbh2jAVgQ4w4snHJf
    tt84W+fOI+pxalSVDagBFaLwHyKfPHX9Bhi8MTpY1TocvhGQzUgB3LhdJP547iFI
    8+wbZ3UIGE8BfFRF9oDhTKRm5TgayIPMSNxNdmMF+HpuMoZiiM4eLocaBfTTkAkN
    lyeMdHQRdBv9FtCeCghQjYm5OunzSCkJFA87lNRlnoWpi8g0PQ42gpQNWhcq/DEr
    FS9afPHB6VL59HwDX2beQpyHYhe0VeA/lm+nudt4EQKBgQD+5SFGywCTxBRhtEPD
    ooWbylkcuBJgrCAbzN9xvkab4P6LU3VwA+8Gx0s5ViIXz0JCpFCzwSxRqR9TD2QE
    TST0iF7CwakoS5y0V83nMg84w5101ZiroXiG2xFNK7v6Dlz6BIUyzot7VS2/BnYE
    LJPfPyF0QVKEi3Vvm3EJE7qDVQKBgQDAKU+86l3vopVgQAKWakc3crQ1V0cLbBdp
    aUjW2W7KvNs69XqnIAWqwqV9QJmldGCiPu7tMc9trE2FmhGfsCjb+yqlCj+LIY9I
    og7TRBoiI0OjR8hmDqK8t6JoXtH7YxkNxFzIOOUlemN5TD/cF4sLAQl03tDj7jFB
    fF8iElhipQKBgD3jE/lEQJef+/Lc+bb+NsJkls5KQuwF3qXhUD8lm68tKaBaWyEf
    U2Gp8bGyIAT35XaYvp9mP4R0M47PJdGFiXt1wMw4iQGnmhyPVQbVOKznkctUMQU6
    5zCW79R00eccpaZugoibbXI8dCb1QqIw0JZblZvMYGSeF51JeGBj0d0hAoGAaH9O
    rGYq9SDN6IyGm7NpzP5kf0laCh0a0ij+AlA1jqyK75IExBOG4Wh+RBG4PCCAWFqu
    5XAb5AE6GvhAsz1ByvbYJu3exlNWruHp+/th1sSkiIuFr/Ivjz6xY96EhBdMzY7G
    Ad/mxK28oH7Vj2OCKlbDBLoSkJC8Wmc++LFPPT0CgYA6g7GWBiuK7Pe1RWcCUKP2
    PdW448guhaIAgi9uP6g9aaqH8A8w2saxmOy2FDCporGXHPjf+TrvPUn4CvztmB3E
    GVMtp/4lVRqYobLNB5Og89fH+/RHW8X5zcPA2XDNQ2dkABGqNXh7wsGaV3Jq4ckK
    8zZaZ/oW66X+qtpmyJqT2g==
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv1T7DDt7Ms6TyC/BQ7dK
    jeMeuej0uEyMByws+E9eJ4rLKqcduC/mVhE+1McAJmtUOtc1m+HCQLjwWcd8ZIVN
    rnHQb1mpsWwdp/QMCrkGKAvY47gj+nyuo0CY3/mlh/5Wx0BcuZ72zJdX7On9XgFR
    teLNDHLfX5niuCPlQnULz32kTlz6vJDKHUha3bQfcaoGkJy17Ey7HKk0XwhHt6I5
    A0cLdeO7SZzngPMuvAJEY9U9rRJ+B/6zT7u0WZvWRamFaEPRLzePEaf1rtoCNXQF
    aOdHsBI5r73bh0wApb9IdG4oSvua6K5M+S90ZDNE550Vng7D8mAyl0f2pTYKPLUv
    yQIDAQAB
    -----END PUBLIC KEY-----
