spring.application.name=authservice
server.port=8001

# Database Configuration - Sử dụng user riêng cho AuthService
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket?currentSchema=auth_schema
spring.datasource.username=auth_user
spring.datasource.password=auth_password_123

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=auth_schema
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Đảm bảo schema được tạo nếu chưa tồn tại
spring.sql.init.mode=always

# JWT Configuration - RSA Keys
jwt.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGXWEsjiTZQ7GE\nk1vG7S9DpaYvb0S09CwpOeoeXwZnlK0xtDc8NDHvd0Uz97OboHpAkDGBncByKO+i\nfxs6Oj4Hq2qe4h7oXKAi16+4M0pZTf55JH9RSASGmmOoSw3vjUIZMjJh84jqkImQ\nvci7moO4dW56/WKNjQKd6hZRe/Sd0x3fD/899GYHgNmp3hdrfLa2iyvP04VBJRFh\n+LpPsV01+oDWL94v4Z7aYomG4sG/Sc1nA1T4G5+E5axmc3mGDUOPphEZ/1BS9ID6\niTNpGkCfHsTy6TYH4muF+lm8NnjBbG47W6BYVTVBMbN30QbLvlgP2bPB7z3L6s+9\nbVq3F2oBAgMBAAECggEAXRF94LY2YruIg9/RjSVGajJDpPjLHy16tMMH7cT+z8Vp\ndysLSVNh5G0symOa4Ncr1LPyjlJR8x3yxOZnA2xFIzsRVMdZ4gJnXcGdn8psxTa7\nQOJXW+7ytKamQFUqjizUCNdM3TkykX9ME91/W0n1KCvssIbG4Qv6YNXuL7/9Nrh9\neo46tYtbGhWqfwgM5/YiCnObM6Ypbx6JznCbO9rJkCcPHbC1OPyOcIMcBq0Y+rub\nmQG3+qjFgIX15UqJO+njRtIo+MhGWWKRaluQx3VeUY5uUykbM4h4kH5mTJjMxz+X\njkZK9xHJN1UQtATqkuzoa5M8Xi1V370c2KN+jxlbWwKBgQDuobm6IiBFUBWuUuwP\nAE+CCmbRcNp9pNL0RvaECUPlam9aRX1kiSziSu+T3QF3GQcKJq4J67u1VtQ1S4bJ\nrN49XJ6XKaknztFXZikqRyzt2s+E7QPeuaNY+KiaMRA7SRaVHJlcs43RfGZGXbQN\np0uXqwcqL6uJqdYaR0fK0oV1IwKBgQDUzWKMS2efgfdK9FlZnTNgAJqlani5Gypy\naw9ixpvHo2ApzUNmWc7wGGWHtHPZpKlbPzCfhV9xah8ED0+XPQCoRbELtU5RkHKM\ne/ojLMHnJ6C6yq0nFBHa8yItaql6TPwnX6iByHKmN/XfvrSPm7eH2tHp11HNecU+\njZWrPvDwiwKBgCZJdnYh0ZGtZr0getVxVFBmANcrxzKPhnVBCX5nyif96r3OFm9R\n/wyTv1q3A+wq7NE5IYVf+C8BLm0aoBatkL7BpIRWX9iOO1JNht9Mqi3DhLYsHQnY\nORgmVU7f/l20vVXRT93qxR9OWU6C7EeghuVfwHeJTHl68Won86HcIyOHAoGAETPx\nTYoi/GATT7nlJztwFci2t7yduckaa1mASunnWgI5GegAFNwZwIsYWhoaa3PGRRwc\noCi2CIMdssRSGNXTocbQgzPK+wkEWZsEI6fQnRE1CySrTsdukhapoqZGwR5MHBq9\nkpBTxGAtvkK6cgmSkqb75T2E3WmEqoPjn45dB/UCgYEAlldghgF9BbyeFvidxwVv\n9sbrA2py6DezU8gZFo/5BKGnAecT7l6e7MqIqWpL8LED9MH2RhKnUEJsmX0awDlJ\n635pV91kuIeeSfrsq658uY0DmEP8lmTew+J0lkiGYfYVwVrVyOadIUcODswv7LJp\npVGNeFTVp3Dsr/OUsOQJgHc=\n-----END PRIVATE KEY-----
jwt.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxl1hLI4k2UOxhJNbxu0v\nQ6WmL29EtPQsKTnqHl8GZ5StMbQ3PDQx73dFM/ezm6B6QJAxgZ3Acijvon8bOjo+\nB6tqnuIe6FygItevuDNKWU3+eSR/UUgEhppjqEsN741CGTIyYfOI6pCJkL3Iu5qD\nuHVuev1ijY0CneoWUXv0ndMd3w//PfRmB4DZqd4Xa3y2tosrz9OFQSURYfi6T7Fd\nNfqA1i/eL+Ge2mKJhuLBv0nNZwNU+BufhOWsZnN5hg1Dj6YRGf9QUvSA+okzaRpA\nnx7E8uk2B+JrhfpZvDZ4wWxuO1ugWFU1QTGzd9EGy75YD9mzwe89y+rPvW1atxdq\nAQIDAQAB\n-----END PUBLIC KEY-----
jwt.expiration=3600000

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.show-actuator=false